// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	A                    uint64   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    uint64   `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddRequest) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddResponse struct {
	Result               uint64   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type IsAnagramRequest struct {
	Str1                 string   `protobuf:"bytes,1,opt,name=str1,proto3" json:"str1,omitempty"`
	Str2                 string   `protobuf:"bytes,2,opt,name=str2,proto3" json:"str2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAnagramRequest) Reset()         { *m = IsAnagramRequest{} }
func (m *IsAnagramRequest) String() string { return proto.CompactTextString(m) }
func (*IsAnagramRequest) ProtoMessage()    {}
func (*IsAnagramRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{2}
}

func (m *IsAnagramRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAnagramRequest.Unmarshal(m, b)
}
func (m *IsAnagramRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAnagramRequest.Marshal(b, m, deterministic)
}
func (m *IsAnagramRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAnagramRequest.Merge(m, src)
}
func (m *IsAnagramRequest) XXX_Size() int {
	return xxx_messageInfo_IsAnagramRequest.Size(m)
}
func (m *IsAnagramRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAnagramRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAnagramRequest proto.InternalMessageInfo

func (m *IsAnagramRequest) GetStr1() string {
	if m != nil {
		return m.Str1
	}
	return ""
}

func (m *IsAnagramRequest) GetStr2() string {
	if m != nil {
		return m.Str2
	}
	return ""
}

type IsAnagramResponse struct {
	AnagramBool          bool     `protobuf:"varint,1,opt,name=anagramBool,proto3" json:"anagramBool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAnagramResponse) Reset()         { *m = IsAnagramResponse{} }
func (m *IsAnagramResponse) String() string { return proto.CompactTextString(m) }
func (*IsAnagramResponse) ProtoMessage()    {}
func (*IsAnagramResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b9900dc883ea68, []int{3}
}

func (m *IsAnagramResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAnagramResponse.Unmarshal(m, b)
}
func (m *IsAnagramResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAnagramResponse.Marshal(b, m, deterministic)
}
func (m *IsAnagramResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAnagramResponse.Merge(m, src)
}
func (m *IsAnagramResponse) XXX_Size() int {
	return xxx_messageInfo_IsAnagramResponse.Size(m)
}
func (m *IsAnagramResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAnagramResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAnagramResponse proto.InternalMessageInfo

func (m *IsAnagramResponse) GetAnagramBool() bool {
	if m != nil {
		return m.AnagramBool
	}
	return false
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "pb.AddResponse")
	proto.RegisterType((*IsAnagramRequest)(nil), "pb.IsAnagramRequest")
	proto.RegisterType((*IsAnagramResponse)(nil), "pb.IsAnagramResponse")
}

func init() { proto.RegisterFile("calc.proto", fileDescriptor_a2b9900dc883ea68) }

var fileDescriptor_a2b9900dc883ea68 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xdf, 0x4b, 0xc7, 0x20,
	0x14, 0xc5, 0xf3, 0xdb, 0x58, 0x75, 0x17, 0xfd, 0xb8, 0x54, 0x8c, 0x3d, 0x0d, 0x21, 0xd8, 0xd3,
	0xa0, 0x45, 0x10, 0xbd, 0xad, 0xb7, 0x5e, 0xed, 0x2f, 0xd0, 0x29, 0x11, 0xac, 0x69, 0xea, 0xfa,
	0xfb, 0x63, 0xea, 0x6a, 0xec, 0xcd, 0xf3, 0xf1, 0xdc, 0x73, 0x3d, 0x02, 0x0c, 0x7c, 0x1c, 0x5a,
	0x63, 0xb5, 0xd7, 0x78, 0x30, 0x82, 0x36, 0x00, 0xbd, 0x94, 0x4c, 0x7d, 0xcf, 0xca, 0x79, 0x3c,
	0x07, 0xc2, 0x4b, 0x52, 0x93, 0x26, 0x63, 0x84, 0x2f, 0x4a, 0x94, 0x87, 0xa8, 0x04, 0xbd, 0x87,
	0x22, 0x38, 0x9d, 0xd1, 0x93, 0x53, 0x78, 0x07, 0xb9, 0x55, 0x6e, 0x1e, 0x7d, 0xf2, 0x27, 0x45,
	0x5f, 0xe0, 0xea, 0xcd, 0xf5, 0x13, 0xff, 0xb0, 0xfc, 0x6b, 0x8d, 0x45, 0xc8, 0x9c, 0xb7, 0x0f,
	0xc1, 0x79, 0xc6, 0xc2, 0x39, 0xb1, 0x2e, 0xe4, 0x47, 0xd6, 0xd1, 0x27, 0xb8, 0xde, 0xcc, 0xa6,
	0x45, 0x35, 0x14, 0x3c, 0xa2, 0x57, 0xad, 0xc7, 0x90, 0x71, 0xca, 0xb6, 0xa8, 0x33, 0xa1, 0xc3,
	0xbb, 0xb2, 0x3f, 0x9f, 0x83, 0xc2, 0x06, 0x8e, 0x7b, 0x29, 0xf1, 0xa2, 0x35, 0xa2, 0xfd, 0xaf,
	0x56, 0x5d, 0xfe, 0xe9, 0x98, 0x4b, 0x8f, 0xf0, 0x19, 0x4e, 0xd2, 0x32, 0xbc, 0x59, 0x6e, 0xf7,
	0xef, 0xae, 0x6e, 0x77, 0x74, 0x9d, 0x14, 0x79, 0xf8, 0xc0, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1b, 0x2e, 0xf9, 0x74, 0x4e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Anagram(ctx context.Context, in *IsAnagramRequest, opts ...grpc.CallOption) (*IsAnagramResponse, error)
}

type addServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddServiceClient(cc *grpc.ClientConn) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/pb.AddService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) Anagram(ctx context.Context, in *IsAnagramRequest, opts ...grpc.CallOption) (*IsAnagramResponse, error) {
	out := new(IsAnagramResponse)
	err := c.cc.Invoke(ctx, "/pb.AddService/Anagram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Anagram(context.Context, *IsAnagramRequest) (*IsAnagramResponse, error)
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedAddServiceServer) Anagram(ctx context.Context, req *IsAnagramRequest) (*IsAnagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Anagram not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AddService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_Anagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAnagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Anagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AddService/Anagram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Anagram(ctx, req.(*IsAnagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AddService_Add_Handler,
		},
		{
			MethodName: "Anagram",
			Handler:    _AddService_Anagram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc.proto",
}
